[package]
name = "prooheckcp/nodefusion"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"      # Fusion, our Client side UI framework